builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: kafkacli

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
